### PR TITLE
Add flow, Windows: add downloaddir option, make installer cacheable

### PR DESCRIPTION
**Pull request by mdeweerd**
@frederic34 
I see that you updated this project yesterday to correct the download link.
I've added cachability today.
I'll be a nice addition to speed up the action (after adding the directory to cache) and not put as much load on the download server.

### CODE REVIEW

**Comment by frederic34** [comment]
@mdeweerd workflow on dolibarr get stuck on download of archive, rate limit ?

**Comment by frederic34** [comment]
it was blocking on the install

**Comment by mdeweerd** [comment]
Maybe there should be a partial mirror for dolibarr with a secret to download from it and download from it with an extra option to this action to set the head of the server url + part of the GET parameters where the value is "KEY=VALUE" to hold the token.
That with the cache option should avoid us the download issues (the installation could block because the download was partial or just indicating some rate limit was exceeded=.

**Comment by frederic34** [comment]
the command line with msiexec was wrong https://github.com/frederic34/setup-mariadb/commit/59f279d4a8b8182433732e5ead8cb359af9909ff

**Pull request merged**
